# Movie Recommendation

In [52]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import warnings
warnings.filterwarnings('ignore')

In [53]:
df = pd.read_csv('movies_metadata.csv')
df

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",http://www.imdb.com/title/tt6209470/,439050,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,...,NaN,0.0,90.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,Rising and falling between a man and woman,Subdue,False,4.0,1.0
45462,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,111109,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,...,2011-11-17,0.0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,False,9.0,3.0
45463,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",...,2003-08-01,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,False,3.8,6.0
45464,False,NaN,0,[],NaN,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",...,1917-10-21,0.0,87.0,[],Released,NaN,Satan Triumphant,False,0.0,0.0
45465,False,NaN,0,[],NaN,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,...,2017-06-09,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,False,0.0,0.0

In [54]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [55]:
df.isnull().sum().sort_values(ascending=False)

belongs_to_collection    40972
homepage                 37684
tagline                  25054
overview                   954
poster_path                386
runtime                    263
status                      87
release_date                87
imdb_id                     17
original_language           11
spoken_languages             6
title                        6
video                        6
vote_average                 6
revenue                      6
vote_count                   6
popularity                   5
production_companies         3
production_countries         3
original_title               0
id                           0
genres                       0
budget                       0
adult                        0
dtype: int64

In [56]:
df['poster_path'][0]

'/rhIRbceoE9lR4veEXuwCC2wARtG.jpg'

In [57]:
df['homepage'][0]

'http://toystory.disney.com/toy-story'

In [58]:
df['tagline'][1]

'Roll the dice and unleash the excitement!'

In [59]:
df.duplicated().sum()

13

In [60]:
df = df.drop_duplicates().reset_index(drop=True)

In [61]:
df.duplicated().sum()

0

In [62]:
df = df[['title','overview','tagline','genres','vote_average','popularity']]

In [63]:
df

,title,overview,tagline,genres,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",NaN,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,"[{'id': 35, 'name': 'Comedy'}]",5.7,8.387519
...,...,...,...,...,...,...
45448,Subdue,Rising and falling between a man and woman.,Rising and falling between a man and woman,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",4.0,0.072051
45449,Century of Birthing,An artist struggles to finish his work while a...,NaN,"[{'id': 18, 'name': 'Drama'}]",9.0,0.178241
45450,Betrayal,"When one of her hits goes wrong, a professiona...",A deadly game of wits.,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",3.8,0.903007
45451,Satan Triumphant,"In a small town live two brothers, one a minis...",NaN,[],0.0,0.003503
45452,Queerama,50 years after decriminalisation of homosexual...,NaN,[],0.0,0.163015

In [64]:
df.isnull().sum().sort_values(ascending=False)

tagline         25045
overview          954
title               6
vote_average        6
popularity          5
genres              0
dtype: int64

In [65]:
df = df.dropna(subset=['title'])

In [66]:
df['overview'] = df['overview'].fillna('')

In [67]:
import ast

In [68]:
df['genres'][0]

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [69]:
df['genres'] = df['genres'].apply(lambda x : " ".join([i['name']for i in ast.literal_eval(x)]))

In [70]:
df

,title,overview,tagline,genres,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",NaN,Animation Comedy Family,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,Adventure Fantasy Family,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,Romance Comedy,6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,Comedy Drama Romance,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,Comedy,5.7,8.387519
...,...,...,...,...,...,...
45448,Subdue,Rising and falling between a man and woman.,Rising and falling between a man and woman,Drama Family,4.0,0.072051
45449,Century of Birthing,An artist struggles to finish his work while a...,NaN,Drama,9.0,0.178241
45450,Betrayal,"When one of her hits goes wrong, a professiona...",A deadly game of wits.,Action Drama Thriller,3.8,0.903007
45451,Satan Triumphant,"In a small town live two brothers, one a minis...",NaN,,0.0,0.003503
45452,Queerama,50 years after decriminalisation of homosexual...,NaN,,0.0,0.163015

In [71]:
df.isnull().sum().sort_values(ascending=False)

tagline         25039
title               0
overview            0
genres              0
vote_average        0
popularity          0
dtype: int64

In [72]:
df['tagline'] = df['tagline'].fillna('')

In [73]:
df.isnull().sum().sort_values(ascending=False)

title           0
overview        0
tagline         0
genres          0
vote_average    0
popularity      0
dtype: int64

In [74]:
df['tags'] = df['overview']+ " " + df['genres'] + " "+ df['tagline']

In [75]:
df.head()

,title,overview,tagline,genres,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",,Animation Comedy Family,7.7,21.946943,"Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,Adventure Fantasy Family,6.9,17.015539,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,Romance Comedy,6.5,11.7129,A family wedding reignites the ancient feud be...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,Comedy Drama Romance,6.1,3.859495,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,Comedy,5.7,8.387519,Just when George Banks has recovered from his ...

In [76]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [77]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\LENOVO\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\LENOVO\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [78]:
stop_word = set(stopwords.words('english'))

In [79]:
lemmatizer = WordNetLemmatizer()

In [80]:
stop_word

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [81]:
df['tags'][1]

"When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures. Adventure Fantasy Family Roll the dice and unleash the excitement!"

In [82]:
def text_preprocessor (text):
    text = str(text).lower()
    text = re.sub(r'[^A-Za-z\s]' ,'',text)
    words = text.split()
    words = [word for word in words if word not in stop_word]
    words = [lemmatizer.lemmatize(word) for word in words]
    return " ".join(words)

In [83]:
df['tags'] = df['tags'].apply(text_preprocessor)

In [84]:
df['tags'][1]

'sibling judy peter discover enchanted board game open door magical world unwittingly invite alan adult who trapped inside game year living room alans hope freedom finish game prof risky three find running giant rhinoceros evil monkey terrifying creature adventure fantasy family roll dice unleash excitement'

In [85]:
df.head()

,title,overview,tagline,genres,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",,Animation Comedy Family,7.7,21.946943,led woody andys toy live happily room andys bi...
1,Jumanji,When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,Adventure Fantasy Family,6.9,17.015539,sibling judy peter discover enchanted board ga...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,Romance Comedy,6.5,11.7129,family wedding reignites ancient feud nextdoor...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,Comedy Drama Romance,6.1,3.859495,cheated mistreated stepped woman holding breat...
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,Comedy,5.7,8.387519,george bank recovered daughter wedding receive...

In [86]:
df = df.reset_index(drop=True)

In [87]:
df.tail()

,title,overview,tagline,genres,vote_average,popularity,tags
45442,Subdue,Rising and falling between a man and woman.,Rising and falling between a man and woman,Drama Family,4.0,0.072051,rising falling man woman drama family rising f...
45443,Century of Birthing,An artist struggles to finish his work while a...,,Drama,9.0,0.178241,artist struggle finish work storyline cult pla...
45444,Betrayal,"When one of her hits goes wrong, a professiona...",A deadly game of wits.,Action Drama Thriller,3.8,0.903007,one hit go wrong professional assassin end sui...
45445,Satan Triumphant,"In a small town live two brothers, one a minis...",,,0.0,0.003503,small town live two brother one minister one h...
45446,Queerama,50 years after decriminalisation of homosexual...,,,0.0,0.163015,year decriminalisation homosexuality uk direct...

In [88]:
indices = pd.Series(df.index ,index= df['title']).drop_duplicates()
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Subdue                         45442
Century of Birthing            45443
Betrayal                       45444
Satan Triumphant               45445
Queerama                       45446
Length: 45447, dtype: int64

In [89]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [90]:
tfidf = TfidfVectorizer(max_features=50000 , ngram_range=(1,2) , stop_words= 'english' )

In [91]:
tfidf_matrix = tfidf.fit_transform(df['tags'])

In [92]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1548566 stored elements and shape (45447, 50000)>

In [93]:
from sklearn.metrics.pairwise import cosine_similarity

In [94]:
def recommend(title , n=10):
    if title not in indices:
        return ['Movie not found']
    idx = indices[title]
    sim_cosin = cosine_similarity(tfidf_matrix[idx] , tfidf_matrix).flatten()
    similar_idx = sim_cosin.argsort()[::-1][1:n+1]
    return df['title'].iloc[similar_idx]

In [99]:
recommend('Avatar',20)

26547                                      Avatar 2
26553                                Thor: Ragnarok
13883                          The Inhabited Island
43431                        Moontrap: Target Earth
6414     Lara Croft Tomb Raider: The Cradle of Life
14119                          The Three Musketeers
20372                                        Désiré
28403                        France société anonyme
43983                           Nightmare City 2035
28633                          Stand by Me Doraemon
7472                           Frank Herbert's Dune
2457                                     The Matrix
9949                             A Trip to the Moon
29976                                     Shakedown
21567                The Secret of the Third Planet
17997                         The War of the Robots
3656                              Project Moon Base
2551                                The Mole People
16331                           On the Silver Globe
17491                                 Almighty Thor
Name: title, dtype: object

In [100]:
import pickle

In [102]:
pickle.dump(tfidf_matrix,open('tfidf_matrix.pkl' , 'wb'))

pickle.dump(indices ,open('indices.pkl' , 'wb'))

df.to_pickle('df.pkl')

pickle.dump(tfidf,open('tfidf.pkl' , 'wb'))